version: '3'

services: 
    testenv:
      image: backtest
      container_name: backend
      build: 
        context: .
        dockerfile: Dockerfiletest
      environment:
        WAIT_HOSTS: database:27017

    database:
        image: mongo
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: horondi
        expose:
            - 27017
